package gamut

import (
	"image/color"

	colorful "github.com/lucasb-eyer/go-colorful"
	"github.com/muesli/clusters"
)

// A ColorGenerator checks whether a point in the three dimensional CIELab space
// is suitable for color generation.
type ColorGenerator interface {
	Valid(col colorful.Color) bool
	Granularity() (l, c float64)
}

// BroadGranularity is used for wider color spaces, e.g. by the PastelGenerator
type BroadGranularity struct {
}

// FineGranularity is used for tighter color spaces, e.g. by the SimilarHueGenerator
type FineGranularity struct {
}

// SimilarHueGenerator produces colors with a similar hue as the given color
type SimilarHueGenerator struct {
	FineGranularity
	Color color.Color
}

// WarmGenerator produces "warm" colors
type WarmGenerator struct {
	BroadGranularity
}

// HappyGenerator produces "happy" colors
type HappyGenerator struct {
	BroadGranularity
}

// PastelGenerator produces "pastel" colors
type PastelGenerator struct {
	BroadGranularity
}

// Granularity returns BroadGranularity's default values
func (g BroadGranularity) Granularity() (l, c float64) {
	_ = "STUB: not implemented"

	// Granularity returns FineGranularity's default values
	return 0, 0
}

func (g FineGranularity) Granularity() (l, c float64) {
	_ = "STUB: not implemented"

	// distanceDegrees returns the distance between two angles on a circle
	// e.g. the distance between 5 degrees and 355 degress is 10, not 350
	return 0, 0
}

func distanceDegrees(a1, a2 float64) float64 { _ = "STUB: not implemented"; return 0 }

// Valid returns true if the given color has a similar hue as the original color
func (gen SimilarHueGenerator) Valid(col colorful.Color) bool {
	_ = "STUB: not implemented"
	return false
}

// Valid returns true if the color is considered a "warm" color
func (cc WarmGenerator) Valid(col colorful.Color) bool { _ = "STUB: not implemented"; return false }

// Valid returns true if the color is considered a "happy" color
func (cc HappyGenerator) Valid(col colorful.Color) bool { _ = "STUB: not implemented"; return false }

// Valid returns true if the color is considered a "pastel" color
func (cc PastelGenerator) Valid(col colorful.Color) bool { _ = "STUB: not implemented"; return false }

// ColorObservation is a wrapper around colorful.Color, implementing the
// clusters.Observation interface
type ColorObservation struct {
	colorful.Color
}

// Coordinates returns the data points of a Lab color value
func (c ColorObservation) Coordinates() clusters.Coordinates {
	_ = "STUB: not implemented"
	return *new(clusters.Coordinates)
}

// Distance calculates the distance between two ColorObservations in the Lab
// color space
func (c ColorObservation) Distance(pos clusters.Coordinates) float64 {
	_ = "STUB: not implemented"
	return 0
}

// Generate returns a slice with the requested amount of colors, generated by
// the provided ColorGenerator.
func Generate(count int, generator ColorGenerator) ([]color.Color, error) {
	_ = "STUB: not implemented"
	// Create data points in the CIE L*a*b color space
	// l for lightness channel
	// a, b for color channels
	return nil, nil
}

// col = colorful.Hcl(a*360.0, b, c)

// Enable graph generation (.png files) for each iteration
// km, _ := kmeans.NewWithOptions(0.02, Plotter{})

// Partition the color space into multiple clusters
